# Generated by Django 4.2.5 on 2023-09-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='book_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publisher',
        ),
    ]
